import express from "express";
import path from "path";
import { createServer as createViteServer } from "vite";
import { GoogleGenAI } from "@google/genai";
import dotenv from "dotenv";

dotenv.config();

const app = express();
const PORT = 3000;

app.use(express.json({ limit: "10mb" }));

// Lazy initialize Gemini client
function getGeminiClient(): GoogleGenAI | null {
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) {
    console.warn("GEMINI_API_KEY is not set. Using smart fallback heuristic agent.");
    return null;
  }
  return new GoogleGenAI({
    apiKey,
    httpOptions: {
      headers: {
        "User-Agent": "aistudio-build",
      },
    },
  });
}

// Health check endpoint
app.get("/api/health", (req, res) => {
  res.json({ status: "ok", app: "Hasebha - احسبها", timestamp: new Date().toISOString() });
});

// Hasebha AI Accountant Agent endpoint
app.post("/api/ai/agent", async (req, res) => {
  try {
    const { message, history = [], currentContext = {}, language = "en" } = req.body;
    const ai = getGeminiClient();

    const systemPrompt = `You are "Hasebha AI" (حاسبها الذكي), the premier elite autonomous AI Accountant & Financial Agent built inside the Hasebha mobile application for small business owners, freelancers, agencies, and merchants (specifically tailored for Egyptian & Middle Eastern business owners with full Arabic & English support, Egyptian 14% VAT, EGP/USD/SAR currencies, and WhatsApp reminders).

You are NOT just a passive chatbot; you are an ACTION-CAPABLE AGENT that takes concrete actions:
1. Creating invoices directly from voice or conversational requests.
2. Checking for missing required fields (customer name, items, unit price, quantity, payment terms) and asking concise, friendly follow-up questions to complete the task.
3. Drafting personalized, respectful, and effective WhatsApp payment reminders for overdue invoices.
4. Logging expenses with automatic category classification (Purchases, Marketing, Transport, Utilities, Salaries, Rent, Other).
5. Performing real-time business health diagnosis, profit margin analysis, and actionable cash-flow advice.

CURRENT BUSINESS CONTEXT:
${JSON.stringify(currentContext, null, 2)}

PREFERRED LANGUAGE: ${language === "ar" ? "Arabic (Egyptian/Standard business Arabic with friendly tone)" : "English"}

You MUST respond strictly with a valid JSON object matching this schema:
{
  "replyText": "Direct conversational response to the business owner in the requested language",
  "action": "none" | "create_invoice" | "request_missing_info" | "draft_whatsapp_reminder" | "add_expense" | "financial_insight",
  "actionData": {
    // If action is create_invoice:
    "customerName": "string",
    "customerPhone": "string (optional)",
    "items": [{"name": "string", "quantity": number, "price": number}],
    "discount": number,
    "vatRate": 14,
    "paymentTermsDays": number,
    "notes": "string",
    "isComplete": boolean,
    "missingFields": ["string"] // e.g., ["price", "quantity", "customerName"]
    
    // If action is draft_whatsapp_reminder:
    "invoiceId": "string",
    "customerName": "string",
    "customerPhone": "string",
    "amountDue": number,
    "currency": "EGP",
    "reminderMessage": "Custom ready-to-send WhatsApp message text in Arabic/English",
    "urgency": "polite" | "urgent" | "final_notice"

    // If action is add_expense:
    "title": "string",
    "amount": number,
    "category": "Purchases" | "Marketing" | "Transport" | "Utilities" | "Salaries" | "Rent" | "Other",
    "date": "YYYY-MM-DD",
    "notes": "string"

    // If action is financial_insight:
    "insightType": "profit_boost" | "cashflow_alert" | "tax_saving" | "debt_collection",
    "summary": "string",
    "recommendedActions": ["string"]
  }
}

Do NOT wrap the JSON in markdown code fences (\`\`\`json). Just return raw valid JSON.`;

    if (!ai) {
      // Fallback rule-based agent if no API key provided
      const lower = (message || "").toLowerCase();
      let fallbackReply = language === "ar" 
        ? "أهلاً بك يا فندم! أنا محاسبك الذكي احسبها. كيف أساعدك اليوم في إدارة فواتيرك ومصروفاتك؟" 
        : "Welcome! I am your Hasebha AI Accountant. How can I assist you with your invoices, expenses, or cash flow today?";
      let action = "none";
      let actionData: any = {};

      if (lower.includes("فاتورة") || lower.includes("invoice") || lower.includes("create")) {
        action = "create_invoice";
        fallbackReply = language === "ar"
          ? "تم تجهيز مسودة الفاتورة! ما هو اسم العميل وقيمة الأصناف؟"
          : "I've started drafting an invoice! What is the customer name and items with prices?";
        actionData = {
          customerName: "Ahmed Trading",
          customerPhone: "+201012345678",
          items: [{ name: "Consulting / Products", quantity: 1, price: 1500 }],
          discount: 0,
          vatRate: 14,
          paymentTermsDays: 15,
          notes: "Auto-generated by Hasebha AI",
          isComplete: false,
          missingFields: ["price", "item_details"]
        };
      } else if (lower.includes("تذكير") || lower.includes("whatsapp") || lower.includes("remind") || lower.includes("late") || lower.includes("overdue")) {
        action = "draft_whatsapp_reminder";
        fallbackReply = language === "ar"
          ? "قمت بإنشاء رسالة تذكير مهذبة واحترافية للعميل عبر واتساب. يمكنك إرسالها بضغطة زر!"
          : "I've crafted a professional WhatsApp payment reminder. You can send it with a single tap!";
        actionData = {
          invoiceId: "INV-2026-003",
          customerName: "Ahmed Trading",
          customerPhone: "+201012345678",
          amountDue: 12750,
          currency: "EGP",
          reminderMessage: language === "ar"
            ? "مرحباً أستاذ أحمد، نود تذكيركم بموعد استحقاق الفاتورة رقم INV-2026-003 بقيمة 12,750 ج.م. رابط الفاتورة والدفع: https://hasebha.app/pay/inv-003. شاكرين لتعاملكم الراقي!"
            : "Hello Mr. Ahmed, a friendly reminder regarding overdue invoice INV-2026-003 for EGP 12,750. View & pay online: https://hasebha.app/pay/inv-003. Thank you!",
          urgency: "polite"
        };
      } else if (lower.includes("مصروف") || lower.includes("expense") || lower.includes("صرفت") || lower.includes("paid")) {
        action = "add_expense";
        fallbackReply = language === "ar"
          ? "تم تسجيل المصروف بنجاح وتصنيفه في الميزانية."
          : "Expense recorded successfully and categorized in your ledger.";
        actionData = {
          title: "Office Supplies / Marketing",
          amount: 450,
          category: "Purchases",
          date: new Date().toISOString().split("T")[0],
          notes: "Recorded via Voice/Chat"
        };
      }

      return res.json({ replyText: fallbackReply, action, actionData });
    }

    // Call Gemini 3.7 Flash
    const formattedHistory = history.map((h: any) => ({
      role: h.role === "user" ? "user" : "model",
      parts: [{ text: typeof h.content === "string" ? h.content : JSON.stringify(h.content) }]
    }));

    const response = await ai.models.generateContent({
      model: "gemini-3.7-flash",
      contents: [
        ...formattedHistory,
        {
          role: "user",
          parts: [{ text: `User query: "${message}". Process this and return the strict action JSON.` }]
        }
      ],
      config: {
        systemInstruction: systemPrompt,
        responseMimeType: "application/json",
        temperature: 0.3,
      }
    });

    const text = response.text || "{}";
    try {
      const parsed = JSON.parse(text);
      return res.json(parsed);
    } catch (e) {
      return res.json({
        replyText: text,
        action: "none",
        actionData: {}
      });
    }
  } catch (error: any) {
    console.error("AI Agent error:", error);
    res.status(500).json({ error: error.message || "Failed to process AI request" });
  }
});

// Automated Monthly Financial Deep Analysis
app.post("/api/ai/analyze", async (req, res) => {
  try {
    const { financialData, language = "en" } = req.body;
    const ai = getGeminiClient();

    if (!ai) {
      return res.json({
        healthScore: 88,
        healthStatus: "Strong & Growing",
        executiveSummary: language === "ar" 
          ? "أداؤك المالي هذا الشهر ممتاز مع نمو 18.4% في صافي الأرباح، ولكن يوصى بتحصيل المبالغ المتأخرة (18,400 ج.م) لتحسين التدفق النقدي."
          : "Outstanding financial performance this month with an 18.4% increase in net profit. Focus on collecting the 18,400 EGP in outstanding receivables to optimize cash liquidity.",
        keyStrengths: [
          language === "ar" ? "نسبة تحصيل قوية تصل إلى 86%" : "Strong collection rate of 86%",
          language === "ar" ? "انخفاض المصروفات التشغيلية بنسبة 8.3%" : "Operating expenses reduced by 8.3%",
          language === "ar" ? "متوسط سرعة التحصيل 28 يوم" : "Average collection velocity of 28 days"
        ],
        actionableRecommendations: [
          language === "ar" ? "إرسال تذكيرات واتساب لفواتير أحمد تريدنج والنور سنتر لتسريع تحصيل 21,650 ج.م" : "Send WhatsApp automated reminders for Ahmed Trading & El Nour Store to unlock 21,650 EGP",
          language === "ar" ? "تجهيز الإقرار الضريبي للقيمة المضافة (14%) قبل نهاية الشهر" : "Prepare 14% VAT quarterly reconciliation ahead of due deadline",
          language === "ar" ? "استثمار فائض السيولة (42,850 ج.م) في توسيع مخزون المنتجات الأكثر مبيعاً" : "Deploy net cash surplus (42,850 EGP) into high-turnover inventory"
        ],
        cashFlowForecast: [
          { month: "Sep 2026", projectedRevenue: 105000, projectedExpenses: 36000, projectedNet: 69000 },
          { month: "Oct 2026", projectedRevenue: 118000, projectedExpenses: 38000, projectedNet: 80000 },
          { month: "Nov 2026", projectedRevenue: 130000, projectedExpenses: 41000, projectedNet: 89000 }
        ]
      });
    }

    const response = await ai.models.generateContent({
      model: "gemini-3.7-flash",
      contents: `Perform an executive monthly financial analysis for this small business in ${language === "ar" ? "Arabic" : "English"}.
Financial snapshot: ${JSON.stringify(financialData)}`,
      config: {
        systemInstruction: `You are Hasebha Senior Financial Analyst. Analyze the small business data with real mathematical clarity, cash flow risks, profit opportunities, and tax compliance (14% VAT). Return strictly JSON with keys: healthScore (0-100), healthStatus (string), executiveSummary (string), keyStrengths (array of strings), actionableRecommendations (array of strings), cashFlowForecast (array of {month, projectedRevenue, projectedExpenses, projectedNet}).`,
        responseMimeType: "application/json",
      }
    });

    const parsed = JSON.parse(response.text || "{}");
    res.json(parsed);
  } catch (error: any) {
    console.error("AI Analysis error:", error);
    res.status(500).json({ error: error.message });
  }
});

// Dynamic WhatsApp payment reminder generator
app.post("/api/ai/generate-reminder", async (req, res) => {
  try {
    const { customerName, invoiceNumber, amountDue, dueDate, currency = "EGP", tone = "friendly", language = "ar" } = req.body;
    const ai = getGeminiClient();

    if (!ai) {
      const msg = language === "ar"
        ? `مرحباً أستاذ ${customerName}، تحية طيبة من فريق العمل 🌸\nنود تذكيركم بلطف بموعد استحقاق الفاتورة رقم (${invoiceNumber}) بقيمة ${amountDue.toLocaleString()} ${currency}.\nيمكنكم الاطلاع على الفاتورة والدفع فوراً عبر الرابط التالي:\nhttps://hasebha.app/pay/${invoiceNumber}\nشاكرين لتعاونكم الدائم معنا!`
        : `Dear ${customerName},\nGreetings! This is a gentle reminder regarding invoice #${invoiceNumber} for ${currency} ${amountDue.toLocaleString()} due on ${dueDate}.\nYou can view details and settle online here:\nhttps://hasebha.app/pay/${invoiceNumber}\nThank you for your business!`;
      return res.json({ reminderText: msg });
    }

    const response = await ai.models.generateContent({
      model: "gemini-3.7-flash",
      contents: `Write a customized, high-converting WhatsApp payment reminder for customer ${customerName}, invoice ${invoiceNumber}, amount ${amountDue} ${currency}, due ${dueDate}. Tone: ${tone}. Language: ${language === "ar" ? "Egyptian/Arabic" : "English"}. Keep it concise, friendly, and include the payment link https://hasebha.app/pay/${invoiceNumber}. Return only the exact message text ready to send.`,
    });

    res.json({ reminderText: response.text?.trim() });
  } catch (error: any) {
    console.error("Reminder generator error:", error);
    res.status(500).json({ error: error.message });
  }
});

// Start server with Vite middleware
async function startServer() {
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), "dist");
    app.use(express.static(distPath));
    app.get("*", (req, res) => {
      res.sendFile(path.join(distPath, "index.html"));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Hasebha Server running on http://0.0.0.0:${PORT}`);
  });
}

startServer();
